name: ML CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'data/**' # Trigger jika ada perubahan di folder data
      - 'src/**' # Trigger jika ada perubahan di folder src

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train model (CI)
        run: |
          python src/model_training.py
          # Verifikasi model.pkl berhasil dibuat
          ls -l model.pkl

      - name: Test model (CI)
        run: python src/model_testing.py

      - name: Commit and push new model (CD)
        if: success() # Lanjutkan hanya jika langkah sebelumnya berhasil
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add model.pkl # Tambahkan model baru ke staging
          git commit -m '🤖 Update machine learning model' || echo 'No changes to commit'
          git push